Repository labstudydev/Chamelezone, pull requests merged in 2019-12, with the labels that each got.

#8 Repository, RemoteDataSource 구조 생성, 패키지 구조 변경, 장소 상세 페이지, 리뷰 등록/수정 페이지 수정
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/yeonae/chamelezone/adapter/PagerAdapter.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/MemberRepository.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/sourse/remote/MemberRemoteDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/CourseResponse.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/LikeResponse.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/ReviewResponse.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/MapTabFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/place/PlaceDetailActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/place/PlaceReviewTabFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/place/adapter/PlaceDetailPagerAdapter.kt
  app/src/main/java/com/yeonae/chamelezone/view/review/ReviewCreateActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/review/ReviewModifyFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_place_detail.xml
  app/src/main/res/layout/fragment_place_info_tab.xml
  app/src/main/res/layout/fragment_place_review_tab.xml
  app/src/main/res/layout/fragment_review_modify.xml
  app/src/main/res/layout/item_place_list.xml
Labels: Merge Needed

#11 ImagePicker 메세지 수정, gladle 주석, 홈 탭 place item 수정, 장소 상세 페이지에 정보, 리뷰 화면 ViewPager, FrameLayout 수정
  app/build.gradle
  app/src/main/java/com/yeonae/chamelezone/adapter/PagerAdapter.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/MemberRepository.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/repositroy/MemberRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/sourse/remote/MemberRemoteDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/view/NonSwipeViewPager.kt
  app/src/main/java/com/yeonae/chamelezone/view/home/HomeActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/home/HomeTabFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/place/PlaceDetailActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/review/ReviewCreateActivity.kt
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/activity_course_register.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_course.xml
  app/src/main/res/layout/activity_my_place.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/activity_place_detail.xml
  app/src/main/res/layout/activity_place_register.xml
  app/src/main/res/layout/activity_review_create.xml
  app/src/main/res/layout/activity_user_modify.xml
  app/src/main/res/layout/fragment_confirm_email.xml
  app/src/main/res/layout/fragment_course_modify.xml
  app/src/main/res/layout/fragment_course_tab.xml
  app/src/main/res/layout/fragment_find_email.xml
  app/src/main/res/layout/fragment_find_password.xml
  app/src/main/res/layout/fragment_home_tab.xml
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_like_tab.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_map_tab.xml
  app/src/main/res/layout/fragment_mypage_tab.xml
  app/src/main/res/layout/fragment_place_info_tab.xml
  app/src/main/res/layout/fragment_place_modify.xml
  app/src/main/res/layout/fragment_place_review_tab.xml
  app/src/main/res/layout/fragment_review_modify.xml
  app/src/main/res/layout/item_place_list.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed

#12 marker 클릭시 info fragment 구현, my place에 더보기 버튼 클릭시 수정, 삭제 구현
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/member/MemberRemoteDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/member/MemberRemoteDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/place/PlaceRemoteDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/place/PlaceRemoteDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/view/home/HomeActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/MapTabFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/MarkerInfoFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/mypage/myplace/MyPlaceActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/mypage/myplace/adapter/MyPlaceRvAdapter.kt
  app/src/main/res/layout/fragment_map_tab.xml
  app/src/main/res/layout/fragment_marker_info.xml
  app/src/main/res/layout/item_my_place.xml
  app/src/main/res/menu/pop_up_menu.xml
Labels: Merge Needed

#13 tedPermission lib 적용
  .idea/codeStyles/Project.xml
  app/src/main/java/com/yeonae/chamelezone/data/repository/member/MemberRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/place/PlaceRepository.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/place/PlaceRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/review/ReviewLocalDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/review/ReviewLocalDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/member/MemberRemoteDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/member/MemberRemoteDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/place/PlaceRemoteDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/place/PlaceRemoteDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/review/ReviewRemoteDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/remote/review/ReviewRemoteDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/MemberResponse.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/PlaceResponse.kt
  app/src/main/java/com/yeonae/chamelezone/view/home/HomeActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/GpsPermission.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/MapTabFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: Answer Needed

#14 TedPermission 적용 및 Message 수정
  app/src/main/java/com/yeonae/chamelezone/data/repository/course/CourseRepository.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/course/CourseRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/review/ReviewRepository.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/review/ReviewRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/course/CourseLocalDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/course/CourseLocalDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/like/LikeLocalDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/like/LikeLocalDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/review/ReviewLocalDataSource.kt
  app/src/main/java/com/yeonae/chamelezone/data/source/local/review/ReviewLocalDataSourceImpl.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/PlaceResponse.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/MapTabFragment.kt
  app/src/main/res/values/strings.xml
Labels: Merge Needed

#15 코스등록 - 장소검색 체크박스 구현
  .idea/codeStyles/Project.xml
  app/src/main/java/com/yeonae/chamelezone/data/repository/place/PlaceRepository.kt
  app/src/main/java/com/yeonae/chamelezone/data/repository/place/PlaceRepositoryImpl.kt
  app/src/main/java/com/yeonae/chamelezone/view/course/CourseRegisterActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/course/PlaceChoiceFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/course/adapter/PlaceChoiceRvAdapter.kt
  app/src/main/res/drawable/btn_check.xml
  app/src/main/res/drawable/ic_check_black_24dp.xml
  app/src/main/res/drawable/ic_check_color_24dp.xml
  app/src/main/res/drawable/ic_close_black_24dp.xml
  app/src/main/res/layout/activity_course_register.xml
  app/src/main/res/layout/activity_place_register.xml
  app/src/main/res/layout/fragment_keyword_tab.xml
  app/src/main/res/layout/fragment_place_choice.xml
  app/src/main/res/layout/item_place_choice.xml
Labels: Review Needed

#18 EditText 스크롤 적용, 장소상세페이지 스크롤 시 뒤로가기 버튼 예외처리
  app/src/main/java/com/yeonae/chamelezone/adapter/ImageViewPagerAdapter.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/MapTabFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/place/PlaceDetailActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/review/ReviewModifyFragment.kt
  app/src/main/res/layout/activity_place_detail.xml
  app/src/main/res/layout/activity_review_create.xml
  app/src/main/res/layout/fragment_place_info_tab.xml
  app/src/main/res/layout/fragment_review_modify.xml
  app/src/main/res/layout/slider_image.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed

#19 나의 장소 - 더보기 버튼 생성 및 수정, 지도 - 검색어 없을 시 예외처리, 장소 검색 - 키워드 클릭시 activity로 키워드 전달
  app/src/main/java/com/yeonae/chamelezone/network/api/MemberApi.kt
  app/src/main/java/com/yeonae/chamelezone/network/api/PlaceApi.kt
  app/src/main/java/com/yeonae/chamelezone/network/api/RetrofitConnection.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/KeywordResponse.kt
  app/src/main/java/com/yeonae/chamelezone/network/model/MemberResponse.kt
  app/src/main/java/com/yeonae/chamelezone/view/login/JoinFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/map/MapTabFragment.kt
  app/src/main/java/com/yeonae/chamelezone/view/mypage/myplace/MyPlaceActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/mypage/myplace/PlaceRegisterActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/mypage/myplace/SearchAddressActivity.kt
  app/src/main/java/com/yeonae/chamelezone/view/mypage/myplace/adapter/MyPlaceRvAdapter.kt
  app/src/main/res/drawable/btn_check.xml
  app/src/main/res/drawable/btn_corner.xml
  app/src/main/res/drawable/draw.xml
  app/src/main/res/drawable/ic_check_black_24dp.xml
  app/src/main/res/drawable/ic_check_gray_24dp.xml
  app/src/main/res/drawable/ic_check_orange_24dp.xml
  app/src/main/res/drawable/search_box_draw.xml
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/activity_course_register.xml
  app/src/main/res/layout/activity_my_place.xml
  app/src/main/res/layout/activity_place_register.xml
  app/src/main/res/layout/activity_search_address.xml
  app/src/main/res/layout/fragment_keyword_tab.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/item_course_list.xml
  app/src/main/res/layout/item_my_place.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Answer Needed
